# Generated by Django 5.0 on 2024-01-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50)),
                ('image', models.CharField()),
                ('token', models.CharField()),
                ('wins', models.SmallIntegerField()),
                ('loses', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type_game', models.CharField(max_length=50)),
                ('list_player', models.ManyToManyField(to='pong.user')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=50)),
                ('date_game', models.DateTimeField()),
                ('duration_game', models.DurationField()),
                ('type_game', models.CharField(max_length=50)),
                ('in_game', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pong.tournament')),
                ('list_player', models.ManyToManyField(db_column='list_player', related_name='list_player', to='pong.user')),
                ('losers', models.ManyToManyField(db_column='losers', related_name='losers', to='pong.user')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='pong.user')),
            ],
        ),
    ]
