# Generated by Django 5.0 on 2024-01-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_2auth',
            field=models.BooleanField(default=False),
        ),
    ]
