# Generated by Django 3.2.23 on 2024-02-20 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('pseudo', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, null=True)),
                ('register', models.BooleanField(default=False)),
                ('secret_2auth', models.CharField(max_length=100)),
                ('has_2auth', models.BooleanField(default=False)),
                ('token_auth', models.CharField(max_length=100)),
                ('wins', models.SmallIntegerField()),
                ('loses', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type_game', models.CharField(max_length=50)),
                ('list_player', models.ManyToManyField(to='back.User')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=50)),
                ('date_game', models.DateTimeField()),
                ('duration_game', models.DurationField()),
                ('type_game', models.CharField(max_length=50)),
                ('in_game', models.BooleanField(default=False)),
                ('list_player', models.ManyToManyField(db_column='list_player', related_name='list_player', to='back.User')),
                ('losers', models.ManyToManyField(db_column='losers', related_name='losers', to='back.User')),
                ('tournament', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.tournament')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='back.user')),
            ],
        ),
    ]
