# Generated by Django 3.2.23 on 2024-02-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_access',
            field=models.BooleanField(default=False),
        ),
    ]
