# Generated by Django 3.2.23 on 2024-02-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
