# Generated by Django 3.2.23 on 2024-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20240205_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_2auth',
            field=models.CharField(max_length=100),
        ),
    ]
