# Generated by Django 3.2.23 on 2024-02-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_alter_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.avatar'),
        ),
    ]
