# Generated by Django 3.2.23 on 2024-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_rename_avatar_id_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
