# Generated by Django 3.2.23 on 2024-02-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_alter_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
