# Generated by Django 3.2.23 on 2024-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_avatar_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(max_length=255, upload_to='avatars'),
        ),
    ]
