# Generated by Django 3.2.24 on 2024-02-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_auto_20240225_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(max_length=2000, upload_to='avatars'),
        ),
    ]
