# Generated by Django 3.2.23 on 2024-02-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_auto_20240225_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image_url',
            new_name='image_url_42',
        ),
    ]
