# Generated by Django 3.2.23 on 2024-02-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_rename_image_url_avatar_image_url_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='avatar_update',
            field=models.BooleanField(default=False),
        ),
    ]
