# Generated by Django 3.2.23 on 2024-02-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0017_avatar_avatar_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.AddField(
            model_name='user',
            name='password_tournament',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
