# Generated by Django 3.2.24 on 2024-02-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_auto_20240227_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_tournament',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
