# Generated by Django 3.2.23 on 2024-02-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0020_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='offline', max_length=20),
        ),
    ]
