# Generated by Django 3.2.24 on 2024-03-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_jwt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
