# Generated by Django 3.2.24 on 2024-02-29 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0022_auto_20240229_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='loses',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='wins',
            field=models.SmallIntegerField(default=0),
        ),
    ]
