# Generated by Django 3.2.25 on 2024-03-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0024_auto_20240303_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_players', models.SmallIntegerField(default=2)),
                ('score', models.CharField(max_length=10)),
                ('date', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GameTTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draw', models.BooleanField(default=False)),
                ('date', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='list_player',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='type_game',
        ),
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='back.user'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='list_player_other',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='list_player_user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner_t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_t', to='back.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='aliasname',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(default='Default Tournament', max_length=30),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='gamettt',
            name='draw_user1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draw_user1', to='back.user'),
        ),
        migrations.AddField(
            model_name='gamettt',
            name='draw_user2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draw_user2', to='back.user'),
        ),
        migrations.AddField(
            model_name='gamettt',
            name='loser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loserttt', to='back.user'),
        ),
        migrations.AddField(
            model_name='gamettt',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winnerttt', to='back.user'),
        ),
        migrations.AddField(
            model_name='gamepong',
            name='loser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loserpong', to='back.user'),
        ),
        migrations.AddField(
            model_name='gamepong',
            name='loser2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loserpong2', to='back.user'),
        ),
        migrations.AddField(
            model_name='gamepong',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.tournament'),
        ),
        migrations.AddField(
            model_name='gamepong',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winnerpong', to='back.user'),
        ),
    ]
