# Generated by Django 3.2.25 on 2024-03-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0025_auto_20240304_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loses',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='wins',
            field=models.SmallIntegerField(default=0),
        ),
    ]
