# Generated by Django 3.2.25 on 2024-03-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0027_auto_20240305_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
    ]
