# Generated by Django 3.2.25 on 2024-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0028_auto_20240307_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='limit_status',
            field=models.CharField(default='09:41', max_length=20),
        ),
    ]
